import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/layout/MainHeader";
import { DarkModeProvider } from "@/context/DarkModeContext";

const inter = Inter({ subsets: ["latin"] });

const gms = localFont({
  src: "../../public/fonts/GmarketSansMedium.otf",
  display: "swap",
  variable: "--font-gms",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={gms.variable}>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className="dark:bg-[#2F2F2F] font-gms">
        <script
          id="theme-provider"
          dangerouslySetInnerHTML={{
            __html: `
              const darkModeSetting = localStorage.getItem("dark-mode");
              if (darkModeSetting === "true") {
                document.documentElement.classList.add("dark");
              } else {
                document.documentElement.classList.remove("dark");
              }
            `,
          }}
        ></script>
        <DarkModeProvider>
          <MainHeader />
          {children}
        </DarkModeProvider>
      </body>
    </html>
  );
}
